### ISSUE TITLE
Issue with Application Gateway Ingress Controller

### ISSUE THREAD

**Issue by lambertpandian** [kedacore/http-add-on#1096]
### Report

I am trying to migrate the ingress controller from Nginx to Azure Application Gateway. The following is my ingress configuration. I get a 404 Not Found error. Azure Application gateway tries to connect to keda-add-ons-http-interceptor pod for health probe and it is failing, I have attached the screenshot
```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    meta.helm.sh/release-name: xkcd
    meta.helm.sh/release-namespace: keda-tester
  creationTimestamp: "2024-07-17T06:55:08Z"
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: xkcd-dev
  namespace: keda
  resourceVersion: "118833"
  uid: 0d93e746-8789-424a-a043-5d90952e9f72
spec:
  ingressClassName: azure-application-gateway
  rules:
  - host: kedatester.mydomain.net
    http:
      paths:
      - backend:
          service:
            name: keda-add-ons-http-interceptor-proxy
            port:
              number: 8080
        path: /
        pathType: Prefix
```
Azure App gateway health screenshot
<img width="680" alt="image" src="https://github.com/user-attachments/assets/1e1faec5-7ba1-487c-9bfc-7d20ffa8f93b">

### Expected Behavior

Http Addon needs to work with Azure Application Gateway ingress controller.

### Actual Behavior

Http Addon is not working with Azure Application Gateway ingress controller.

### Steps to Reproduce the Problem

1. Install xkcd example with ingressClassName: azure-application-gateway
2. Connect to the end point

### Logs from KEDA HTTP operator

```
example
```

### HTTP Add-on Version

0.8.0

### Kubernetes Version

1.28

### Platform

Microsoft Azure

**Comment by JorTurFer** [comment]
Hello,
The problem is that currently we check the user agent to discover if the request is a probe or not and handle it as probe and not as a legit request:
https://github.com/kedacore/http-add-on/blob/08c811fe205daaf2bc55c6a46155be2729f21916/interceptor/middleware/routing.go#L85-L89

Does AGIC support adding custom user agent to the probe? if yes, just use `kube-probe` and it'll pass. If not, we will need to include the AGIC user agent. Do you know which is it? Are you willing to open a PR supporting it?
