### ISSUE TITLE
Move Docker images to ghcr.io/kedacore/http-add-on/*

### ISSUE THREAD

**Issue by tomkerkhove** [kedacore/http-add-on#567]
As of today, our images are structured as following:
![image](https://user-images.githubusercontent.com/4345663/211252336-7d9f8cf3-38b8-4726-8f8b-79eb2f75dc57.png)

Which you can pull through:
```
docker pull ghcr.io/kedacore/http-add-on-interceptor
```

However, I'm wondering if we should change them to the following before v1.0:
```diff
- ghcr.io/kedacore/http-add-on-interceptor
+ ghcr.io/kedacore/http-add-on/interceptor
- ghcr.io/kedacore/http-add-on-operator
+ ghcr.io/kedacore/http-add-on/operator
- ghcr.io/kedacore/http-add-on-scaler
+ ghcr.io/kedacore/http-add-on/scaler
```

**Comment by JorTurFer** [comment]
I'm not 100% sure if GH supports the extra segment (I think so), but dockerhub doesn't support it, Contributors who are working in the repo and need to publish their images can't do `IMAGE_REGISTRY=docker.io IMAGE_REPO=jorturfer make docker-publish`, they would need to override the full qualified name for each image. 
It's not a problem because it's supported, but maybe it's a side effect we haven't considered yet

**Comment by tomkerkhove** [comment]
Yes, you can definitely do this in GHCR.

I personally think it's worth the change to provide some structure but it's not a must. @kedacore/keda-maintainers @kedacore/keda-http-maintainers ?

**Comment by JorTurFer** [comment]
We can do it if there isn't any objection, my only concern is about developer experience, but I can think about how to make it easier

**Comment by tomkerkhove** [comment]
Agreed

**Comment by zroubalik** [comment]
Closing.
