### ISSUE TITLE
Operator Fails to Delete `scaledObject`

### ISSUE THREAD

**Issue by similark** [kedacore/http-add-on#662]
### Report

When we create an `Httpscaledobject` with a name different than the referenced Deployment, the operator will create a `Scaledobject` with the same name as the `Httpscaledobject`. But, upon deletion of the `Httpscaledobject`, the operator tries to delete the `Scaledobject` by the wrong name - that is, the name of the referenced `Deployment`, as can be seen in both these lines:
https://github.com/kedacore/http-add-on/blob/b5c41c8c2a97db4b4c1d25de0b4a7a26ae22f400/operator/controllers/scaled_object.go#L31
https://github.com/kedacore/http-add-on/blob/b5c41c8c2a97db4b4c1d25de0b4a7a26ae22f400/operator/controllers/app.go#L48

### Expected Behavior

The Operator should look up for the `Scaledobject` by the exact same logic every time. i.e. when looking for the `Scaledobject` to delete, search for one with the same name as the `Httpscaledobject`, as done when creating it....

### Actual Behavior

Described above. Operator does NOT delete the `Scaledobject`

### Steps to Reproduce the Problem

1. Kind of straightforward to reproduce

### Logs from KEDA HTTP operator

2023-04-24T11:19:50Z	INFO	controllers.HTTPScaledObject	App ScaledObject not found, moving on

### What version of the KEDA HTTP Add-on are you running?

0.4.0

### Kubernetes Version

1.23

### Platform

Any

**Comment by tomkerkhove** [comment]
Can you please try using 0.5 and see if it still an issue please?

**Comment by JorTurFer** [comment]
Thanks for reporting it ❤️ 

To prevent this case, we have introduced the ownership in the underlying ScaledObject: https://github.com/kedacore/http-add-on/commit/ce372282d11a28a409086f1493ca1be8e9256ad9

In v0.5.0 it shouldn't happen anymore because when you delete the HTTPScaledObject, kubernetes will remove the generated ScaledObjects in cascade. In this case, I suggest upgrading the add-on to prevent this case in the future and removing the orphan ScaledObject manually. We don't plan any other action to delete those orphan ScaledObjects.

I close the issue as not planned (because it's already addressed), but feel free to reopen it if you still face with this problem in v0.5.0
