### ISSUE TITLE
Wrong syntax in the HTTPScaledObject in example v0.6.0

### ISSUE THREAD

**Issue by yaakov-berkovitch** [kedacore/http-add-on#869]
**Report**
The HTTPScaledObject example for release 0.6.0 failed to deploy

**Expected Behavior**
Expect that the example can be deployed without any errors.

**Actual Behavior**
Using the example (a good short way instead of reading the documentation) from folder example/0.6.0 returns an error:
```text
Error from server (BadRequest): error when creating "/tmp/KK.yaml": HTTPScaledObject in version "v1alpha1" cannot be handled as a HTTPScaledObject: strict decoding error: unknown field "spec.scaleTargetRef.name"
```
After I looked in previous versions, I saw that "deployment" was used, and so I replaced the spec.scaleTargetRef.name by spec.scaleTargetRef.deployment and it works,

**Steps to Reproduce the Problem**
Deploy the HTTPScaledObject from v0.6.0 example folder

**Logs from KEDA HTTP operator**
N/A

**What version of the KEDA HTTP Add-on are you running?**
0.6.0

**Kubernetes Version**
1.27

**Platform**
AWS EKS

**Comment by tomkerkhove** [comment]
I presume you are referring to https://github.com/kedacore/http-add-on/blob/main/examples/v0.6.0/httpscaledobject.yaml? I think it was accidentally using `name` due to https://github.com/kedacore/http-add-on/commit/214431250a552a3835be9699287cc58b6a62e2bb#diff-3de0e1f7f6bd340346cd5323abea4cfca82dc7b8190c676cc35de61a78020e39 and should be `deployment` instead but @JorTurFer can verify

**Comment by JorTurFer** [comment]
Oh, you are totally right, I did a mistake when I added the example. Let me open a PR to fix it

**Comment by JorTurFer** [comment]
This is the fix: https://github.com/kedacore/http-add-on/pull/871
Instead of `name`, use `deployment`

Thanks for reporting! 🙇
